language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - nightly

sudo: false

matrix:
    fast_finish: true

services:
    - mysql

install:
    - composer install

script:
    - ./vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
